import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import {scaleLinear} from 'd3';
import type {ModelKey} from '../models/registry';
import {predictedBISAvailability} from '../models/bisAvailability';
import {lastObservedBIS,parseBIS,parseElapsed,validateBIS,type BISMode,type BISObservation} from '../observations/bis';
import {clock,sampleAt,type Sample} from './scenario';
import {RateEquivalent} from './RateEquivalent';
import type {Kg} from '../models/units';
interface Props {mode:BISMode;onMode:(mode:BISMode)=>void;observations:BISObservation[];onChange:(rows:BISObservation[])=>void;time:number;rows:Sample[];preview:boolean;model:ModelKey;weight:Kg;onSeek:(t:number)=>void}
export function BISPanel({mode,onMode,observations,onChange,time,rows,preview,model,weight,onSeek}:Props){
 const [manual,setManual]=useState(''),[timestamp,setTimestamp]=useState(''),[useNow,setUseNow]=useState(true),[paste,setPaste]=useState(''),[pending,setPending]=useState<BISObservation[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[hover,setHover]=useState<BISObservation|null>(null);
 const host=useRef<HTMLDivElement>(null),[width,setWidth]=useState(700),alive=useRef(true),importVersion=useRef(0);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 useLayoutEffect(()=>{const o=new ResizeObserver(entries=>setWidth(entries[0]!.contentRect.width));if(host.current)o.observe(host.current);return()=>o.disconnect();},[mode]);
 const start=preview?0:Math.max(0,time-20),end=preview?60:Math.max(20,time),x=scaleLinear().domain([start,end]).range([38,width-18]),y=scaleLinear().domain([0,100]).range([165,15]);
 const visible=observations.filter(r=>r.time>=start&&r.time<=(preview?end:time));
 const last=lastObservedBIS(observations,time),point=(hover&&visible.includes(hover)?hover:null)??last,sample=sampleAt(rows,point?.time??time);
 function attempt(fn:()=>void){try{fn();setError('');}catch(e){setError(e instanceof Error?e.message:'Invalid BIS data.');}}
 function previewText(text:string,source:'paste'|'csv'){setPending([]);attempt(()=>{const parsed=parseBIS(text,source);setPending(parsed);setNotice(`Preview ready: ${parsed.length} observations. No data added yet.`);});}
 return <section className="card bis-panel" aria-label="Optional BIS data">
  <div className="section-title"><div><div className="eyebrow">OPTIONAL · SEPARATE FROM PK</div><h2>BIS observations & predictions</h2></div><label className="field">BIS mode<select aria-label="BIS mode" value={mode} onChange={e=>{onMode(e.target.value as BISMode);setHover(null);setError('');}}><option value="none">No BIS</option><option value="predicted">Model-predicted BIS</option><option value="observed">Observed BIS</option></select></label></div>
  <p className="explain">BIS data never change the PK parameters, target sequence or simulated administration. Data remain in this browser tab only; changing applied patient covariates clears observations. Resetting the clock or editing targets preserves observations at their recorded times.</p>
  {mode==='none'&&<p className="bis-empty">Simulation runs without BIS. {observations.length>0?`${observations.length} observations are retained but hidden.`:''}</p>}
  {mode==='predicted'&&<p className="model-caution"><strong>Model-predicted BIS unavailable. </strong>{predictedBISAvailability(model).reason} Observed BIS can still be entered independently.</p>}
  {mode==='observed'&&<>
   <div className="bis-observed-heading"><span className="mini-tag">OBSERVED DATA · USER ENTERED</span><strong>{last?`${last.bis.toFixed(1)} at ${clock(last.time)}`:'No observation at or before the playhead'}</strong></div>
   <p className="explain">{last?'Last recorded observation, not a live reading or a value interpolated to the playhead.':'Add a point or import elapsed-time/BIS pairs.'} Points are unconnected; gaps are not filled. The vertical axis is the BIS index, not an alarm or target range.</p>
   <div ref={host}><svg className="bis-chart" viewBox={`0 0 ${width} 200`} role="img" aria-label="Observed BIS points over elapsed simulation time" onPointerLeave={()=>setHover(null)}>
    {[0,25,50,75,100].map(v=><g key={v}><line className="grid" x1="38" x2={width-18} y1={y(v)} y2={y(v)}/><text x="30" y={y(v)+4} textAnchor="end">{v}</text></g>)}
    {x.ticks(width<500?3:6).map(v=><text key={v} x={x(v)} y="190" textAnchor="middle">{clock(v)}</text>)}
    <line className="playhead" x1={x(time)} x2={x(time)} y1="15" y2="165"/>
    {visible.map(r=><circle key={r.time} cx={x(r.time)} cy={y(r.bis)} r={hover===r?7:5} fill="#356786" tabIndex={0} role="button" aria-label={`Observed BIS ${r.bis} at ${clock(r.time)}; seek`} onPointerEnter={()=>setHover(r)} onFocus={()=>setHover(r)} onBlur={()=>setHover(null)} onClick={()=>onSeek(r.time)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSeek(r.time);}}}/>)}
   </svg></div>
   {point&&<div className="inspection"><span>OBSERVED BIS <b>{point.bis.toFixed(1)} at {clock(point.time)}</b></span><span>Cp <b>{sample.cp.toFixed(3)} µg/mL</b></span><span>Ce <b>{sample.ce.toFixed(3)} µg/mL</b></span><span>Target <b>{sample.target?.toFixed(2)??'—'}</b></span><span>Simulated input <b>{sample.rate.toFixed(2)} mg/min</b><RateEquivalent rate={sample.rate} weight={weight}/></span><span>Total <b>{sample.administered.toFixed(2)} mg</b></span></div>}
   <div className="bis-entry-grid"><form onSubmit={e=>{e.preventDefault();attempt(()=>{if(!manual.trim())throw new Error('Enter a BIS value.');const observation={time:useNow?time:parseElapsed(timestamp),bis:Number(manual),source:'manual' as const};onChange(validateBIS([...observations,observation]));setNotice(`Observed BIS added at ${clock(observation.time)}.`);setManual('');setHover(null);});}}><h3>Add an observation</h3><label className="check"><input type="checkbox" checked={useNow} onChange={e=>setUseNow(e.target.checked)}/>Timestamp at current playhead ({clock(time)})</label>{!useNow&&<label className="field">Elapsed time · min or mm:ss<input aria-label="BIS observation time" value={timestamp} onChange={e=>setTimestamp(e.target.value)} required/></label>}<label className="field">Observed BIS<input aria-label="Observed BIS value" type="number" min="0" max="100" step="any" required value={manual} onChange={e=>setManual(e.target.value)}/></label><button className="save-event">Add observed BIS</button></form>
   <div><h3>Paste or import observations</h3><p className="explain">Two columns only: elapsed minutes (or mm:ss), BIS. Optional header: time_min,bis. CSV, tab or semicolon separators; no patient identifiers.</p><label className="field">Timestamp/BIS pairs<textarea aria-label="Timestamp/BIS pairs" placeholder={'time_min,bis\n0,96\n04:30,52'} value={paste} onChange={e=>{setPaste(e.target.value);importVersion.current++;setPending([]);}}/></label><div className="bis-actions"><button className="save-event" onClick={()=>previewText(paste,'paste')}>Preview pasted data</button><label className="field">Import CSV<input aria-label="Import BIS CSV" type="file" accept=".csv,.tsv,.txt,text/csv,text/plain" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;const version=++importVersion.current;setPending([]);if(file.size>1_000_000){setError('Use a file smaller than 1 MB.');return;}try{const text=await file.text();if(alive.current&&version===importVersion.current)previewText(text,'csv');}catch{if(alive.current&&version===importVersion.current)setError('The file could not be read.');}}}/></label></div>
   {pending.length>0&&<div className="bis-import-preview"><p>{pending.length} observations · {clock(pending[0]!.time)} to {clock(pending.at(-1)!.time)}. First values: {pending.slice(0,5).map(r=>`${clock(r.time)} → ${r.bis}`).join('; ')}.</p><button className="save-event" onClick={()=>attempt(()=>{onChange(validateBIS([...observations,...pending]));setNotice(`${pending.length} observations appended.`);setPending([]);setHover(null);})}>Append {pending.length} observations</button></div>}</div></div>
   {observations.length>0&&<details className="controller-note"><summary>Observation log · {observations.length} points</summary><button className="text-button" onClick={()=>{onChange([]);setHover(null);setNotice('Observed BIS data cleared.');}}>Clear all observed BIS</button><div className="bis-log"><table><thead><tr><th>Elapsed</th><th>Observed BIS</th><th>Source</th><th>Action</th></tr></thead><tbody>{observations.map(r=><tr key={r.time}><td>{clock(r.time)} <small>({r.time.toFixed(4)} min)</small></td><td>{r.bis}</td><td>{r.source}</td><td><button className="text-button" aria-label={`Delete observed BIS at ${r.time} minutes`} onClick={()=>{onChange(observations.filter(p=>p!==r));setHover(null);}}>Delete</button></td></tr>)}</tbody></table></div></details>}
  </>}
  {error&&<p className="error" role="alert">{error}</p>}{mode==='observed'&&notice&&<p className="explain" role="status">{notice}</p>}
 </section>;
}
